### ISSUE TITLE
NControl 0.7.2 on NuGet?

### ISSUE THREAD

**Issue by ghost** [chrfalch/NControl.Controls#11]
I am going to upgrade to Xamarin.Forms 2.0 and I would like to upgrade NControl to the version 0.7.2 using NuGet, but NuGet still does not know the version 0.7.2. When will it be added to NuGet?

**Comment by chrfalch** [comment]
Very soon now! Sorry for the delay!

**Comment by chrfalch** [comment]
0.8.0 should now be available on NuGet :-)

On Thu, Jan 28, 2016 at 11:41 AM, Christian Falch <christian.falch@gmail.com

> wrote:
> 
> Very soon now! Sorry for the delay!
>

**Comment by ghost** [comment]
Thank you.
