### ISSUE TITLE
GalleryView Android 4.1 "smearing"

### ISSUE THREAD

**Issue by woellij** [chrfalch/NControl.Controls#15]
![image](https://cloud.githubusercontent.com/assets/5063919/13123273/b9a574c2-d5bb-11e5-8061-7edf9d5de359.png)

Hi

thanks for the great library - i've successfully used parts of it in an earlier project already and was very grateful for the work that was lifted from my shoulders ;)

At the moment i'm running into a problem using the GalleryView 

On Android 4.1 (Emulator) with Support Libraries it is "smearing" as seen on the screenshot above.
The "smearing" appears after dragging the top view to the left (it leaves the smears behind and the next view isn't visible)

Do you have an idea what could be the cause of it? 

I've tested it on an 5.1.0 Emulator and there it works smoothly without problems.
(Now i camed around to test it on an 4.4.2 Emulator aswell and there it works too. Which at the moment is good enough - though somebody else might run into the issue)

Unfortunately i can't test it on a device at the moment to verify the issue.

**Comment by chrfalch** [comment]
Never seen this before, please see if you can test it on a real device before I do any more investigation. Remember that NControl.Controls is a demonstration library for concepts found in the NControl library.

**Comment by chrfalch** [comment]
Closed - no further results or reproductions.
