### ISSUE TITLE
iOS app freezes when calling NControls.Init()

### ISSUE THREAD

**Issue by renzska** [chrfalch/NControl.Controls#17]
I've been able to trace this freeze on calling NControls.Init() down to a third-party dll that has font files in it causing the Init function to freeze on this line:

https://github.com/chrfalch/NControl.Controls/blob/b60eadbcc71262e287954016882cc234a9837047/NControl.Controls.iOS/NControls.cs#L28

The third-party dll is the Google.SignIn.Dll which has the Roboto font:

![image](https://cloud.githubusercontent.com/assets/13021263/13192593/ea404fe2-d72a-11e5-9023-ce6b70590341.png)

Can you add an overload to the Init function that skips the dynamic loading of the fonts or see if there is a better way that won't cause the same issue? The Init is needed for the linking issue.

Thanks,

John

**Comment by chrfalch** [comment]
Thats Great - would it be possible to get the third party library so that
I can try to fix the source for the error?

**Comment by renzska** [comment]
Here's the library: https://components.xamarin.com/view/googleiossignin

**Comment by renzska** [comment]
I tested further and in a sample project, adding the Google SignIn for iOS component and referencing it works. It's only in my main project that it freezes. I then proceeded to have it skip loading that .ttf and have it try to the load the FontAwesome font from NControl.Controls and it freezes at the same line. I'm unable to share the full project, so I'll do some more digging on my side.

**Comment by renzska** [comment]
I found a solution from this stackoverflow post: http://stackoverflow.com/questions/24900979/cgfontcreatewithdataprovider-hangs-in-airplane-mode

I had to add the following call before the call to CGFont.CreateFromProvider and it worked!:

```
var familyNames = UIFont.FamilyNames;
```

I'm not in airplane mode and I do have internet access on the simulator, so I'm not sure exactly why it works, but it does.

**Comment by Gertjancom** [comment]
@renzska Wow. That fixed my issue (on tvOS) also. Best. Bug. Ever. Thanks.
