### ISSUE TITLE
SvgImage: allow 9-slice SVG rendering

### ISSUE THREAD

**Issue by patridge** [chrfalch/NControl.Controls#23]
[Spun off from a [issue on NGraphics](https://github.com/praeclarum/NGraphics/issues/29#issuecomment-187723921).]

Potential implementation: https://github.com/twintechs/NControl.Controls.SvgImageView

The goal is to allow functionality similar to [9-patch Android image assets](http://developer.android.com/tools/help/draw9patch.html) and [StretchableImage](https://developer.xamarin.com/api/member/UIKit.UIImage.StretchableImage/)/[CreateResizableImage](https://developer.xamarin.com/api/member/MonoTouch.UIKit.UIImage.CreateResizableImage/p/MonoTouch.UIKit.UIEdgeInsets/). Someone consuming the control would set inset values that would dictate corner areas that are preserved while stretching content to render in all the remaining areas.

I've created a control that makes this work (originally based on a [different NGraphics-derived SvgImage](https://github.com/paulpatarinski/Xamarin.Forms.Plugins/tree/master/SVG), but now available in the above [NControl-based solution](https://github.com/twintechs/NControl.Controls.SvgImageView). For more details, check out this blog post describing my [9-slice SVG approach](For more details, check out this blog post describing my 9-slice SVG approach.).

Unfortunately, since this naive 9-slice implementation requires drawing a series of canvases into the final desired canvas, it needs access to the ability to create a platform canvas. (That is why I had to create the custom renderers.) I wasn't sure how to make that work within the NControl system. It looks like NGraphics' next release will offer a `Platforms.Current` to avoid this entirely, but I wanted to put this out there now in case there is a solution available within the current NControl library for generating a platform canvas.

**Comment by chrfalch** [comment]
Great! I'll see if it possible for NControl to expose this functionality.

**Comment by chrfalch** [comment]
Opened up issue in NControl library to allow access to platform services: https://github.com/chrfalch/NControl/issues/52
