### ISSUE TITLE
TabStringControl on iOS

### ISSUE THREAD

**Issue by NelsonSantos** [chrfalch/NControl.Controls#24]
Hi...

First of all, thank's for the great work!!! 

I love your control library, its save much off my work!!

I have looked at TabStripControl and on Android its render great, but on iOS its look  strange, based on its own design.

Are there a way, on iOS, to render them like Segmented Controls using your DrawingFunction method inside the control? Or are there other way?

If there, I would like to apply a design based on twitter profille page, where on the middle there are a Twitt, Media and Like tab. On Android its use tab control and on iOS its use Segmented Control.

I need to know where to draw and not how draw.

Regards

Nelson

**Comment by chrfalch** [comment]
Thanks for the great feedback :-)

The Tab control is built to show some of the possibilities of NControl and its underlying rendering system using NGraphics. Changing it to a full-blown tab control which renders differently on different platforms is not within the scope. The main point is to show how to draw and set up a control with different subviews without using native rendering nor native controls on each platform.

That said, please use the code as a starting point for creating the control you are suggesting, everything is MIT licensed and such a control would be great

I will be closing this issue, but please keep in touch if you take on the task of creating such a control.
