### ISSUE TITLE
WizardLayout xaml support

### ISSUE THREAD

**Issue by InquisitorJax** [chrfalch/NControl.Controls#28]
I know the WizardLayout has just been added - was wondering if xaml definition support is somewhere on the todo list.
Adding views to Pages element in xaml currently throws exception "property Pages is null or not IEnumerable"

`<ncontrols:WizardLayout Page="{Binding WizardSelectedPage}" >
                <ncontrols:WizardLayout.Pages>
                    <views:View1 BindingContext="{Binding View1ViewModel}" />
                            <views:View2 BindingContext="{Binding View2ViewModel}" />           
                </ncontrols:WizardLayout.Pages>
</ncontrols:WizardLayout>`

**Comment by chrfalch** [comment]
Yes, I know - that's an issue - will try to address it.

**Comment by InquisitorJax** [comment]
wow that was fast :) thanks

**Comment by InquisitorJax** [comment]
Hi - is perhaps an est. eta in this issue & the Android Support lib update?
No rush - just wondering when you were planning on getting round to it.

**Comment by chrfalch** [comment]
The Android Support lib update is an issue with Xamarin.Forms and not with NControl.
