### ISSUE TITLE
Xamarin.Forms 2.2+ breaks support for Android

### ISSUE THREAD

**Issue by michaelstonis** [chrfalch/NControl.Controls#29]
Xamarin.Forms 2.2+ introduces a new set of Android support libraries which will break compatibility with libraries that use older versions of Xamarin.Forms. The resolution is to update all projects to add support for 2.2.

**Comment by tlhintoq** [comment]
Are you saying there _is_ a resolution that makes NControls work with Forms 2.2?
Or are you saying Xamarin needs to _creation_ a resolution for all their libraries to be backwards compatible with various NuGets such as NControls?  I'm unclean by what you're statement is saying.

I have a rather exhaustive post on this on the Xamarin forums if anyone has a solution they can detail here and/or there.
http://forums.xamarin.com/discussion/68085/xamarin-forms-2-2-support-libraries-breaks-some-android-nugets-such-as-ncontrol-and-others/p1?new=1

**Comment by InquisitorJax** [comment]
Looks like the root of this issue is Xamarin Forms 2.2 Hard dependency on 23.3 android support libraries.. don't look like that is going to be fixed anytime soon. 
Would be awesome if NContol.Controls could update their dependencies to the newer released android support libraries & Xamarin Forms 2.2+

**Comment by chrfalch** [comment]
Ah, you want MORE than XF 2.2? Like 2.3 to solve this?

**Comment by chrfalch** [comment]
Just spent some time upgrading to XF 2.2:

Release 0.9.3.2
https://github.com/chrfalch/NControl.Controls/releases/tag/0.9.3.2

Should this solve the issue?

**Comment by InquisitorJax** [comment]
... it should... will be checking this evening.

**Comment by InquisitorJax** [comment]
yup - seems like its all good if using the >0.9.3.2 NControls :)
