### ISSUE TITLE
FloatingLabelControl needs to surface the .Focus() event to set the ExtendedEntry focus just like Xamarin.Forms.Entry

### ISSUE THREAD

**Issue by renzska** [chrfalch/NControl.Controls#31]
I am unable to set the focus on the floatingLabelControl. The FloatingLabelControl needs to surface the .Focus() event to set the ExtendedEntry focus just like Xamarin.Forms.Entry.

Thanks.

**Comment by moreirawebmaster** [comment]
I have same problem!
