### ISSUE TITLE
floating label ; xaml

### ISSUE THREAD

**Issue by ghost** [chrfalch/NControl.Controls#34]
the examples for floating label are c# 

how do i implement with XAML?

appreciate any guidance as under pressure to get solution out the door.

**Comment by InquisitorJax** [comment]
include the Ncontrol reference in the root tag:
`xmlns:ncontrols="clr-namespace:NControl.Controls;assembly=NControl.Controls"`

... and then add the xaml element:
`<ncontrols:FloatingLabelControl Placeholder="first name" Text="{Binding FirstName}" />`

**Comment by ghost** [comment]
Uwp support yet so I can run on Windows 10 devices

Sent from my iPhone

On 13 Aug 2016, at 8:57 PM, Malcolm Jack <notifications@github.com<mailto:notifications@github.com>> wrote:

include the Ncontrol reference in the root tag:
xmlns:ncontrols="clr-namespace:NControl.Controls;assembly=NControl.Controls"

... and then add the xaml element:

##
