### ISSUE TITLE
Xaml Examples

### ISSUE THREAD

**Issue by hadhoryth** [chrfalch/NControl.Controls#41]
Could you please give some example of using TabStripControl in xaml. I have already tried but it does not appear 
```xml
xmlns:nct="clr-namespace:NControl.Controls;assembly=NControl.Controls"
<nct:TabStripControl TabBackColor="#FF4A4B" TabIndicatorColor="White" HeightRequest="20">
	<nct:TabStripControl.Children>
	    <nct:TabItem Title="Me">
		   <nct:TabItem.View>
			<StackLayout>
			   <Label Text="View 1"/>
			</StackLayout>
		   </nct:TabItem.View>
	    </nct:TabItem>
	   <nct:TabItem Title="YOU">
		<nct:TabItem.View>
			<StackLayout>
				<Label Text="View 2"/>
			</StackLayout>
		</nct:TabItem.View>
	   </nct:TabItem>
	</nct:TabStripControl.Children>s
</nct:TabStripControl>
```

**Comment by carl-neng** [comment]
Hello sir.  I have a some question?
1. Could you please give some example of using CardPage in xaml. I have already tried but it does not appear
2. I have see ActionButton on android black background when we toggle button. I don't know the problem. Can you help me this problem.

<controls:ExpandableActionButton BackgroundColor="Transparent" Direction="Up"
                      ButtonColor="#FF9800"
                      WidthRequest="65"
                      RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToParent,Property=Width,Constant=-75,Factor=1}"
                      RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent,Property=Height,Factor=0,Constant=-45}">
          <controls:ExpandableActionButton.Buttons>
            <controls:ActionButton BackgroundColor="Transparent" ButtonColor="#009688" ButtonIcon="{x:Static controls:FontAwesomeLabel.FAAddressBook}">
              <controls:ActionButton.HasShadow>
                <OnPlatform x:TypeArguments="x:Boolean" Android="False"/>
              </controls:ActionButton.HasShadow>
            </controls:ActionButton>
            <controls:ActionButton BackgroundColor="Transparent" Command="{Binding VoidMissionCommand}" ButtonColor="#CDDC39" ButtonIcon="{x:Static controls:FontAwesomeLabel.FAArrowCircleRight}">
              <controls:ActionButton.HasShadow>
                <OnPlatform x:TypeArguments="x:Boolean" Android="False"/>
              </controls:ActionButton.HasShadow>
            </controls:ActionButton>
            <controls:ActionButton BackgroundColor="Transparent" ButtonColor="#2196F3" ButtonIcon="{x:Static controls:FontAwesomeLabel.FACalendar}">
              <controls:ActionButton.HasShadow>
                <OnPlatform x:TypeArguments="x:Boolean" Android="True"/>
              </controls:ActionButton.HasShadow>
            </controls:ActionButton>
          </controls:ExpandableActionButton.Buttons>
        </controls:ExpandableActionButton>

**Comment by chrfalch** [comment]
please post in Xamarin.Form forums.
