### ISSUE TITLE
Error With color

### ISSUE THREAD

**Issue by Neiklot** [chrfalch/NControl.Controls#43]
The assignation 

editButton.ButtonColor = Color.FromHex("#E91E63");

Doesn't works with Button type:

 var editButton = new ActionButton();

What I'm doing bad?

Thanks in advance

**Comment by chrfalch** [comment]
Not sure what you are doing wrong - these controls are basically just demonstrations of what can be done; I suggest you download the source code from Github and see if you can find a solution - I'd be more than happy to include a fix in the project.
